apiVersion: v1
kind: ConfigMap
metadata:
  name: app-client-config
data:
  SPRING_DATA_MONGODB_HOST: mongodb
  SPRING_DATA_MONGODB_PORT: "27017"
  SPRING_DATA_MONGODB_DATABASE: tech-chall
  SPRING_PROFILES_ACTIVE: "default"
  LOGGING_LEVEL_ROOT: "INFO"
  SERVER_PORT: "8080"
