apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: client-ms
  labels:
    app: client-ms
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: client-ms
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
